#!/bin/bash
# build-firefox --- Builds and packages the extension.
#
# Copyright (c) 2015 Diffeo
#
# Comments:
#

readonly dir_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "$dir_root/sh/libtools.sh"

! command -v cfx &>/dev/null 2>&1 \
  && >&2 error "\`cfx´ program not found" \
  && exit 1

set -e

mkdir -p "$dir_root/out"
cd "$dir_root/src/browser/extensions/firefox"
info "building Firefox extension"
cfx xpi >/dev/null
mv sortingdesk.xpi "$dir_root/out"
echo "done."