#!/bin/bash
# focus-firefox --- Focus on either the Mozilla Firefox or Tor Browser programs.
#
# Copyright (c) 2015 Diffeo
#
# Comments:
#

readonly dir_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "$dir_root/sh/libtools.sh"

! command -v wmctrl &>/dev/null 2>&1 \
  && >&2 error "\`wmctrl´ program not found" \
  && exit 1

set -e

wmctrl -a "Mozilla Firefox" || wmctrl -a "Tor Browser"