#!/bin/bash
# reload-firefox --- Builds the extension and posts the package to a service
# running on localhost that then refreshes it on a Firebox-based browser.
#
# Copyright (c) 2015 Diffeo
#
# Comments:
#

set -e

function fail() {
  [ ! -z "$2" ] && error "failed to reload extension: $2"
  exit $1
}

readonly dir_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "$dir_root/sh/settings.sh"
source "$dir_root/sh/libtools.sh"
cd "$dir_root/src/browser/extensions/firefox"

info "reloading extension"
"$dir_root/sh/build-firefox" >/dev/null

# Disable exiting immediately if a command fails, since the subsequent wget
# invocation *always* results in an error code.
set +e
wget --post-file="$dir_root/out/sortingdesk.xpi" "$URL_FIREFOX_RELOAD" &>/dev/null
[ $? -eq 8 ] && echo "done." || fail 1 "service failure"