#!/bin/bash
# reset-fcs --- Deletes all feature collections on a Dossier server
#
# Copyright (c) 2015 Diffeo
#
# Comments:
#

readonly dir_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "$dir_root/sh/settings.sh"

echo "I: deleting all feature collections: $URL_DOSSIER_STACK"
echo curl -X DELETE "$URL_DOSSIER_STACK$URL_DOSSIER_STACK_PREFIX/v1/delete-all-fcs"

curl -X DELETE "$URL_DOSSIER_STACK$URL_DOSSIER_STACK_PREFIX/v1/delete-all-fcs"

echo "done."
