#!/bin/bash
# reset-labels --- Deletes all labels on a Dossier server but retains documents.
#
# Copyright (c) 2015 Diffeo
#
# Comments:
#

readonly dir_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "$dir_root/sh/settings.sh"
source "$dir_root/sh/libtools.sh"

info "deleting all labels: $DOSSIER_MODELS_URL"
curl -s -X DELETE "$DOSSIER_MODELS_URL"\
"$DOSSIER_MODELS_URL_PREFIX/v1/delete-all-labels"

echo "done."
