#!/bin/bash
# reset-fcs --- Deletes all feature collections on a Dossier server
#
# Copyright (c) 2015 Diffeo
#
# Comments:
#

readonly dir_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "$dir_root/sh/settings.sh"
source "$dir_root/sh/libtools.sh"

info "deleting all feature collections: $DOSSIER_MODELS_URL"
curl -X DELETE "$DOSSIER_MODELS_URL"\
"$DOSSIER_MODELS_URL_PREFIX/v1/delete-all-fcs"

echo "done."
