#!/bin/bash
# update-deps --- Updates external dependencies used by this project's different
# components
#
# Copyright (c) 2015 Diffeo
#
# Comments:
#

set -e

dir_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"


# Component: SortingDesk
# ---
cd "$dir_root/src/browser/extensions/chrome"

# The user isn't supposed to add anything into the `lib´ directory. We therefore
# assume that all its contents can be removed.
[ -d lib ] && rm lib -rfv
mkdir -vp lib

mkdir lib/SortingCommon -v
mkdir lib/SortingQueue -v
mkdir lib/SortingDesk -v
mkdir lib/dossier.js -v
mkdir lib/CryptoJS -v
mkdir lib/bootstrap/css -vp
mkdir lib/bootstrap/fonts -v
mkdir lib/bootstrap/js -v

# Note: Google Chrom(e|ium) browsers do not support symlinks (!). There is no
# other option but to actually copy, and thus duplicate, the external
# dependencies we need.
cp -v "$dir_root/src/SortingCommon/SortingCommon.js" lib/SortingCommon/
cp -v "$dir_root/src/SortingQueue/SortingQueue.js" lib/SortingQueue/
cp -v "$dir_root/src/SortingDesk/SortingDesk.js" lib/SortingDesk/
cp -v "$dir_root/src/SortingDesk/LabelBrowser.js" lib/SortingDesk/
cp -v "$dir_root/src/SortingDesk/FolderExplorer.js" lib/SortingDesk/
cp -v "$dir_root/src/SortingDesk/api-live.js" lib/SortingDesk/
cp -v "$dir_root/src/dossier.js/Dossier.js" lib/dossier.js/
cp -v "$dir_root/lib/jquery-2.1.1.min.js" lib/
cp -v "$dir_root/lib/CryptoJS-3.1.2/rollups/md5.js" lib/CryptoJS/
cp -v "$dir_root/lib/bootstrap-3.3.1/css/"*.min.css lib/bootstrap/css/
cp -v "$dir_root/lib/bootstrap-3.3.1/fonts/"* lib/bootstrap/fonts/
cp -v "$dir_root/lib/bootstrap-3.3.1/js/"*.min.js lib/bootstrap/js/

# All files inside `lib' are treated as immutable. We therefore make every file
# inside `lib' read-only to prevent accidental changes.
find lib -type f -exec chmod -v =r {} +

echo -e "\ndone."
